source 'https://rubygems.org'
gem 'byebug'
gem 'concurrent-ruby', '~> 1.1'
gem 'connection_pool'
gem 'daemons', '~> 1.2'
gem 'dotenv'
gem 'net-http2', '~> 0.18.0'
gem 'pg', '~> 1.2.3'
gem 'rake', '12.3.0'
gem 'redis', '4.0.1'
gem 'sequel'
gem 'typhoeus', '~> 1.3'
gem 'prometheus-client', '~> 0.4.2'

group :test do
  gem 'rspec'
  gem 'fakeredis'
  gem 'webmock'
  gem 'timecop'
end